import type { Metadata } from "next";
import {Inter} from "next/font/google";
//import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/providers/Providers";

const inter  = Inter({subsets:["latin"]});

/*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
*/

export const metadata: Metadata = {
  title: "Redux App",
  description: "Generated by Piku",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        //className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className = {inter.className}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
